<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Contatos</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- MENU SUPERIOR -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">
                        Menu
                    </a>
                </li>
            </ul>
        </div>
    </nav>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper cadastro">
    <?php echo $this->layout()->content ?>
</div><!-- /.content-wrapper -->

<!-- RODAPÉ -->
<footer class="main-footer">
        <strong>Desenvolvido por IEPTB-TO - 2015-2016 <a target="_blank" href="http://www.ieptbto.com.br/">Módulo Protesto</a></strong>.
      </footer>
</body>
</html>
