<div class="container">
    <form action='' method="POST">
        <div clas="form - group">
            <div class="col-md-6 offset-md-3">
                <?php echo $this->contactForm->getElement('nome');      ?>
                <?php echo $this->contactForm->getElement('email');     ?>
                <?php echo $this->contactForm->getElement('telefone');  ?>
                <?php echo $this->contactForm->getElement('endereco');  ?>                
				<?php echo $this->contactForm->getElement('submit');    ?>
            </div>
        </div>
    </form>
</div>

